### PR TITLE
Scrollbars

### PR DESCRIPTION
**Pull request by alanclarke**
screen shot 2016-04-06 at 14 41 24

@KidkArolis

### CODE REVIEW

**Comment by alanclarke** [comment]
screen shot 2016-04-06 at 14 50 44

**Comment by KidkArolis** [comment]
Hm, that Firefox screenshot looks broken - the red box is clipped off?

**Comment by alanclarke** [comment]
nah its correct, just the screenshot is a bit squished relative to the other screenshot

**Comment by alanclarke** [comment]
i can show you on my screen if you like

**Pull request merged**
